### ISSUE TITLE
Add config option for reply box height

### ISSUE THREAD

**Issue by EntityReborn** [Goctionni/RedditInboxRevamp#28]
The default size of the reply box is fairly small, and users of certain subreddits that do a lot of larger replies could find an increase to the height very useful.

An option discussed would be adding a configuration option that allows a user to specify how tall the edit box should be.

**Comment by Goctionni** [comment]
This is added now, just not live yet (Or rather, you'll now have an on/off toggle that will allow inbox revamp to remember your last use input-height; is that good enough?).

**Comment by EntityReborn** [comment]
That sounds perfect.
